[package]
name = "macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.57", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.0"
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }